### ISSUE TITLE
License

### ISSUE THREAD

**Issue by valtlai** [lumeland/lumeland.github.io#14]
There’s no a `LICENSE` file in the repository. Could we add one? Would it be MIT?

I’m planning to fork Lume to disable some default plugins and to make some changes that are unlikely to be get merged in the original project. I would also fork the docs to reflect these changes, but the repository needs a proper license before I can do it.

The forked project will have a different name and logo, but it will mention that it’s a fork of Lume. The license will remain as MIT. I’m also going to open PRs or issues on the original Lume repository if I make changes that could be relevant for the original project.

**Comment by oscarotero** [comment]
Yes, sure. I just added the LICENSE.

About disabling default plugins, another way is just create [a `mod.js` file](https://github.com/lumeland/lume/blob/master/mod.js) with your default configuration but importing the original Lume modules.

Of course, it's just a suggestion, feel free to fork the project if you like. PRs would be awesome, do you have any change in mind?

**Comment by valtlai** [comment]
Thank you for adding the license, and the info. I have an idea of better `slugify` function and if it works, I can open a PR for it.
